<?php

namespace AppBundle\Repository;

/**
 * ItemTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUnknownType()
    {
        return $this->createQueryBuilder('type')
            ->where('type.name = :unknown')
            ->setParameter(':unknown', 'Unknown')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
