<?php

namespace AppBundle\Repository;

/**
 * SeasonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonalRepository extends \Doctrine\ORM\EntityRepository
{
}
