<?php

namespace AppBundle\Repository;

/**
 * ShoppingListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingListRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActiveItemsOrdered()
    {
        return $this->createQueryBuilder('list')
            ->leftJoin('list.item', 'item')
            ->where('list.isBought = 0')
            ->orderBy('item.name', 'asc')
            ->getQuery()
            ->getResult();
    }
}
