<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Item;
use AppBundle\Entity\ShoppingList;

/**
 * ShoppingListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingListRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return ShoppingList[]
     */
    public function findActiveItemsOrdered()
    {
        return $this->createQueryBuilder('list')
            ->leftJoin('list.item', 'item')
            ->where('list.isBought = 0')
            ->orderBy('item.name', 'asc')
            ->getQuery()
            ->getResult();
    }

    public function findItem(Item $item)
    {
        return $this->createQueryBuilder('list')
            ->where('list.isBought = 0')
            ->andWhere('list.itemId = :itemId')
            ->setParameter(':itemId', $item->getId())
            ->getQuery()
            ->getOneOrNullResult();
    }
}
