security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$tsSOYoqHfgYw6Ly7ExpbH.Yk3GncdI176MYaKzwZSc2c4SHfMo2jS #admin
                        roles: 'ROLE_ADMIN'
                    api:
                        password: $2y$12$E/bqYxYx3lTWP/DYDYzut.UhQZbLlns5xtsWDlLHmOhhTfad8wd9G #somerandomtoken
                        roles: 'ROLE_API'

    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_API }