# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  lcn.weather_forecast_provider.forecast_io.api_token: 5cc8dc652542c04e6c0ea0e08e0bef72
  lcn.weather_forecast_provider.forecast_io.lang: el

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  lcn.weather_forecast.cache:
          class: Doctrine\Common\Cache\PhpFileCache
          arguments: ["%kernel.cache_dir%"]
          calls:
              - [setNamespace, ['lcn_weather_forecast']]
